# Generated by Django 3.2.9 on 2021-12-10 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('publicacao', models.DateField()),
                ('edicao', models.CharField(max_length=50)),
                ('paginas', models.IntegerField()),
                ('sinopse', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Livros',
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('cliente_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.cliente')),
                ('pseudonimo', models.CharField(blank=True, max_length=100, null=True)),
                ('premiado', models.BooleanField()),
                ('parceiro', models.BooleanField()),
                ('books', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.books')),
            ],
            options={
                'verbose_name_plural': 'Autores',
            },
            bases=('app.cliente',),
        ),
    ]
