# Generated by Django 3.2.9 on 2021-12-10 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_author_books'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='books',
        ),
        migrations.AddField(
            model_name='books',
            name='autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.author'),
        ),
        migrations.AlterField(
            model_name='author',
            name='parceiro',
            field=models.BooleanField(choices=[('s', 'sim'), ('n', 'não')]),
        ),
        migrations.AlterField(
            model_name='author',
            name='premiado',
            field=models.BooleanField(choices=[('s', 'sim'), ('n', 'não')]),
        ),
        migrations.AlterField(
            model_name='books',
            name='edicao',
            field=models.CharField(max_length=50, verbose_name='edição'),
        ),
        migrations.AlterField(
            model_name='books',
            name='paginas',
            field=models.IntegerField(verbose_name='quantidade de páginas'),
        ),
        migrations.AlterField(
            model_name='books',
            name='publicacao',
            field=models.DateField(verbose_name='publicação'),
        ),
        migrations.AlterField(
            model_name='books',
            name='sinopse',
            field=models.TextField(blank=True, null=True, verbose_name='sinopse'),
        ),
        migrations.AlterField(
            model_name='books',
            name='titulo',
            field=models.CharField(max_length=200, verbose_name='título'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='habilitado',
            field=models.BooleanField(blank=True, choices=[('s', 'sim'), ('n', 'não')], null=True, verbose_name='habitação'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='nome completo'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='obs',
            field=models.TextField(blank=True, null=True, verbose_name='observação'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='pontuation',
            field=models.IntegerField(blank=True, null=True, verbose_name='pontuação'),
        ),
        migrations.CreateModel(
            name='Albums',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='título')),
                ('publicacao', models.DateField(verbose_name='publicação')),
                ('duracao', models.IntegerField(verbose_name='duração')),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.author')),
            ],
        ),
    ]
