# Generated by Django 3.2.9 on 2021-12-10 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20211210_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='parceiro',
            field=models.BooleanField(choices=[(True, 'sim'), (False, 'não')]),
        ),
        migrations.AlterField(
            model_name='author',
            name='premiado',
            field=models.BooleanField(choices=[(True, 'sim'), (False, 'não')]),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='habilitado',
            field=models.BooleanField(blank=True, choices=[(True, 'sim'), (False, 'não')], null=True, verbose_name='habitação'),
        ),
    ]
