# Generated by Django 3.2.9 on 2021-12-10 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20211210_1830'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='albums',
            options={'verbose_name_plural': 'Albums'},
        ),
    ]
