# Generated by Django 3.2.9 on 2021-12-11 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_albums_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='amigos',
            field=models.ManyToManyField(blank=True, null=True, related_name='_app_cliente_amigos_+', to='app.Cliente'),
        ),
    ]
