# Generated by Django 3.2.9 on 2021-12-11 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_cliente_amigos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='amigos',
            field=models.ManyToManyField(blank=True, related_name='_app_cliente_amigos_+', to='app.Cliente'),
        ),
    ]
